/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.daos;


import com.mgl.jpa.mapping.samples.jooq.tables.Enterpriseuser;
import com.mgl.jpa.mapping.samples.jooq.tables.records.EnterpriseuserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnterpriseuserDao extends DAOImpl<EnterpriseuserRecord, com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser, Long> {

    /**
     * Create a new EnterpriseuserDao without any configuration
     */
    public EnterpriseuserDao() {
        super(Enterpriseuser.ENTERPRISEUSER, com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser.class);
    }

    /**
     * Create a new EnterpriseuserDao with an attached configuration
     */
    public EnterpriseuserDao(Configuration configuration) {
        super(Enterpriseuser.ENTERPRISEUSER, com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>registrationSource IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser> fetchByRegistrationsource(String... values) {
        return fetch(Enterpriseuser.ENTERPRISEUSER.REGISTRATIONSOURCE, values);
    }

    /**
     * Fetch records that have <code>signUpTs IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser> fetchBySignupts(Timestamp... values) {
        return fetch(Enterpriseuser.ENTERPRISEUSER.SIGNUPTS, values);
    }

    /**
     * Fetch records that have <code>creationTs IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser> fetchByCreationts(Timestamp... values) {
        return fetch(Enterpriseuser.ENTERPRISEUSER.CREATIONTS, values);
    }

    /**
     * Fetch records that have <code>lastModificationTs IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser> fetchByLastmodificationts(Timestamp... values) {
        return fetch(Enterpriseuser.ENTERPRISEUSER.LASTMODIFICATIONTS, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser> fetchById(Long... values) {
        return fetch(Enterpriseuser.ENTERPRISEUSER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mgl.jpa.mapping.samples.jooq.tables.pojos.Enterpriseuser fetchOneById(Long value) {
        return fetchOne(Enterpriseuser.ENTERPRISEUSER.ID, value);
    }
}
