/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.daos;


import com.mgl.jpa.mapping.samples.jooq.tables.Regularuser;
import com.mgl.jpa.mapping.samples.jooq.tables.records.RegularuserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegularuserDao extends DAOImpl<RegularuserRecord, com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser, Long> {

    /**
     * Create a new RegularuserDao without any configuration
     */
    public RegularuserDao() {
        super(Regularuser.REGULARUSER, com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser.class);
    }

    /**
     * Create a new RegularuserDao with an attached configuration
     */
    public RegularuserDao(Configuration configuration) {
        super(Regularuser.REGULARUSER, com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>registrationSource IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser> fetchByRegistrationsource(String... values) {
        return fetch(Regularuser.REGULARUSER.REGISTRATIONSOURCE, values);
    }

    /**
     * Fetch records that have <code>signUpTs IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser> fetchBySignupts(Timestamp... values) {
        return fetch(Regularuser.REGULARUSER.SIGNUPTS, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser> fetchById(Long... values) {
        return fetch(Regularuser.REGULARUSER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mgl.jpa.mapping.samples.jooq.tables.pojos.Regularuser fetchOneById(Long value) {
        return fetchOne(Regularuser.REGULARUSER.ID, value);
    }
}
