/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq;


import com.mgl.jpa.mapping.samples.jooq.tables.Avatar;
import com.mgl.jpa.mapping.samples.jooq.tables.Company;
import com.mgl.jpa.mapping.samples.jooq.tables.Document;
import com.mgl.jpa.mapping.samples.jooq.tables.DocumentAuthor;
import com.mgl.jpa.mapping.samples.jooq.tables.Enterpriseuser;
import com.mgl.jpa.mapping.samples.jooq.tables.EnterpriseuserPermission;
import com.mgl.jpa.mapping.samples.jooq.tables.Regularuser;
import com.mgl.jpa.mapping.samples.jooq.tables.Userprofile;
import com.mgl.jpa.mapping.samples.jooq.tables.records.AvatarRecord;
import com.mgl.jpa.mapping.samples.jooq.tables.records.CompanyRecord;
import com.mgl.jpa.mapping.samples.jooq.tables.records.DocumentAuthorRecord;
import com.mgl.jpa.mapping.samples.jooq.tables.records.DocumentRecord;
import com.mgl.jpa.mapping.samples.jooq.tables.records.EnterpriseuserPermissionRecord;
import com.mgl.jpa.mapping.samples.jooq.tables.records.EnterpriseuserRecord;
import com.mgl.jpa.mapping.samples.jooq.tables.records.RegularuserRecord;
import com.mgl.jpa.mapping.samples.jooq.tables.records.UserprofileRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>jpa</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AvatarRecord, Long> IDENTITY_AVATAR = Identities0.IDENTITY_AVATAR;
    public static final Identity<CompanyRecord, Long> IDENTITY_COMPANY = Identities0.IDENTITY_COMPANY;
    public static final Identity<DocumentRecord, Long> IDENTITY_DOCUMENT = Identities0.IDENTITY_DOCUMENT;
    public static final Identity<UserprofileRecord, Long> IDENTITY_USERPROFILE = Identities0.IDENTITY_USERPROFILE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AvatarRecord> KEY_AVATAR_PRIMARY = UniqueKeys0.KEY_AVATAR_PRIMARY;
    public static final UniqueKey<AvatarRecord> KEY_AVATAR_UK_JC6RLWOND8SQBV2WLE8WC8JQ = UniqueKeys0.KEY_AVATAR_UK_JC6RLWOND8SQBV2WLE8WC8JQ;
    public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = UniqueKeys0.KEY_COMPANY_PRIMARY;
    public static final UniqueKey<CompanyRecord> KEY_COMPANY_COMPANY__EMAIL_UIDX = UniqueKeys0.KEY_COMPANY_COMPANY__EMAIL_UIDX;
    public static final UniqueKey<DocumentRecord> KEY_DOCUMENT_PRIMARY = UniqueKeys0.KEY_DOCUMENT_PRIMARY;
    public static final UniqueKey<DocumentAuthorRecord> KEY_DOCUMENT_AUTHOR_DOCUMENT_AUTHOR__DOCUMENTID_AUTHORID_UIDX = UniqueKeys0.KEY_DOCUMENT_AUTHOR_DOCUMENT_AUTHOR__DOCUMENTID_AUTHORID_UIDX;
    public static final UniqueKey<EnterpriseuserRecord> KEY_ENTERPRISEUSER_PRIMARY = UniqueKeys0.KEY_ENTERPRISEUSER_PRIMARY;
    public static final UniqueKey<EnterpriseuserPermissionRecord> KEY_ENTERPRISEUSER_PERMISSION_ENTERPRISEUSER_PERMISSION__ENTERPRISEUSER_PERMISSION_UIDX = UniqueKeys0.KEY_ENTERPRISEUSER_PERMISSION_ENTERPRISEUSER_PERMISSION__ENTERPRISEUSER_PERMISSION_UIDX;
    public static final UniqueKey<RegularuserRecord> KEY_REGULARUSER_PRIMARY = UniqueKeys0.KEY_REGULARUSER_PRIMARY;
    public static final UniqueKey<UserprofileRecord> KEY_USERPROFILE_PRIMARY = UniqueKeys0.KEY_USERPROFILE_PRIMARY;
    public static final UniqueKey<UserprofileRecord> KEY_USERPROFILE_USER_PROFILE__EMAIL_UIDX = UniqueKeys0.KEY_USERPROFILE_USER_PROFILE__EMAIL_UIDX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AvatarRecord, UserprofileRecord> FKK0SJ4GG341GUNW0DXF38X60FO = ForeignKeys0.FKK0SJ4GG341GUNW0DXF38X60FO;
    public static final ForeignKey<DocumentAuthorRecord, DocumentRecord> FKQED3CIVAH38K329W66ILWS6K7 = ForeignKeys0.FKQED3CIVAH38K329W66ILWS6K7;
    public static final ForeignKey<DocumentAuthorRecord, RegularuserRecord> FK7BQOFSQD1N5TPAKBTNWC58X5F = ForeignKeys0.FK7BQOFSQD1N5TPAKBTNWC58X5F;
    public static final ForeignKey<EnterpriseuserRecord, UserprofileRecord> FKMRR9NOVKAQ55WUDE71D8MI3SE = ForeignKeys0.FKMRR9NOVKAQ55WUDE71D8MI3SE;
    public static final ForeignKey<EnterpriseuserPermissionRecord, EnterpriseuserRecord> FKRL7GCV4IWAOP529L1PRF4SM8H = ForeignKeys0.FKRL7GCV4IWAOP529L1PRF4SM8H;
    public static final ForeignKey<RegularuserRecord, UserprofileRecord> FK3WYV5WNI5YL2LL2C75ED2CMRF = ForeignKeys0.FK3WYV5WNI5YL2LL2C75ED2CMRF;
    public static final ForeignKey<UserprofileRecord, CompanyRecord> FK5GU1O4X2CAOFNE9NDBG001YYW = ForeignKeys0.FK5GU1O4X2CAOFNE9NDBG001YYW;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AvatarRecord, Long> IDENTITY_AVATAR = createIdentity(Avatar.AVATAR, Avatar.AVATAR.ID);
        public static Identity<CompanyRecord, Long> IDENTITY_COMPANY = createIdentity(Company.COMPANY, Company.COMPANY.ID);
        public static Identity<DocumentRecord, Long> IDENTITY_DOCUMENT = createIdentity(Document.DOCUMENT, Document.DOCUMENT.ID);
        public static Identity<UserprofileRecord, Long> IDENTITY_USERPROFILE = createIdentity(Userprofile.USERPROFILE, Userprofile.USERPROFILE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AvatarRecord> KEY_AVATAR_PRIMARY = createUniqueKey(Avatar.AVATAR, "KEY_Avatar_PRIMARY", Avatar.AVATAR.ID);
        public static final UniqueKey<AvatarRecord> KEY_AVATAR_UK_JC6RLWOND8SQBV2WLE8WC8JQ = createUniqueKey(Avatar.AVATAR, "KEY_Avatar_UK_jc6rlwond8sqbv2wle8wc8jq", Avatar.AVATAR.USERPROFILE_ID);
        public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = createUniqueKey(Company.COMPANY, "KEY_Company_PRIMARY", Company.COMPANY.ID);
        public static final UniqueKey<CompanyRecord> KEY_COMPANY_COMPANY__EMAIL_UIDX = createUniqueKey(Company.COMPANY, "KEY_Company_company__email_uidx", Company.COMPANY.EMAIL);
        public static final UniqueKey<DocumentRecord> KEY_DOCUMENT_PRIMARY = createUniqueKey(Document.DOCUMENT, "KEY_Document_PRIMARY", Document.DOCUMENT.ID);
        public static final UniqueKey<DocumentAuthorRecord> KEY_DOCUMENT_AUTHOR_DOCUMENT_AUTHOR__DOCUMENTID_AUTHORID_UIDX = createUniqueKey(DocumentAuthor.DOCUMENT_AUTHOR, "KEY_Document_Author_document_author__documentId_authorId_uidx", DocumentAuthor.DOCUMENT_AUTHOR.DOCUMENTID, DocumentAuthor.DOCUMENT_AUTHOR.AUTHORID);
        public static final UniqueKey<EnterpriseuserRecord> KEY_ENTERPRISEUSER_PRIMARY = createUniqueKey(Enterpriseuser.ENTERPRISEUSER, "KEY_EnterpriseUser_PRIMARY", Enterpriseuser.ENTERPRISEUSER.ID);
        public static final UniqueKey<EnterpriseuserPermissionRecord> KEY_ENTERPRISEUSER_PERMISSION_ENTERPRISEUSER_PERMISSION__ENTERPRISEUSER_PERMISSION_UIDX = createUniqueKey(EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION, "KEY_EnterpriseUser_Permission_EnterpriseUser_Permission__enterpriseUser_permission_uidx", EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION.ENTERPRISEUSER, EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION.PERMISSION);
        public static final UniqueKey<RegularuserRecord> KEY_REGULARUSER_PRIMARY = createUniqueKey(Regularuser.REGULARUSER, "KEY_RegularUser_PRIMARY", Regularuser.REGULARUSER.ID);
        public static final UniqueKey<UserprofileRecord> KEY_USERPROFILE_PRIMARY = createUniqueKey(Userprofile.USERPROFILE, "KEY_UserProfile_PRIMARY", Userprofile.USERPROFILE.ID);
        public static final UniqueKey<UserprofileRecord> KEY_USERPROFILE_USER_PROFILE__EMAIL_UIDX = createUniqueKey(Userprofile.USERPROFILE, "KEY_UserProfile_user_profile__email_uidx", Userprofile.USERPROFILE.EMAIL);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AvatarRecord, UserprofileRecord> FKK0SJ4GG341GUNW0DXF38X60FO = createForeignKey(com.mgl.jpa.mapping.samples.jooq.Keys.KEY_USERPROFILE_PRIMARY, Avatar.AVATAR, "FKk0sj4gg341gunw0dxf38x60fo", Avatar.AVATAR.USERPROFILE_ID);
        public static final ForeignKey<DocumentAuthorRecord, DocumentRecord> FKQED3CIVAH38K329W66ILWS6K7 = createForeignKey(com.mgl.jpa.mapping.samples.jooq.Keys.KEY_DOCUMENT_PRIMARY, DocumentAuthor.DOCUMENT_AUTHOR, "FKqed3civah38k329w66ilws6k7", DocumentAuthor.DOCUMENT_AUTHOR.DOCUMENTID);
        public static final ForeignKey<DocumentAuthorRecord, RegularuserRecord> FK7BQOFSQD1N5TPAKBTNWC58X5F = createForeignKey(com.mgl.jpa.mapping.samples.jooq.Keys.KEY_REGULARUSER_PRIMARY, DocumentAuthor.DOCUMENT_AUTHOR, "FK7bqofsqd1n5tpakbtnwc58x5f", DocumentAuthor.DOCUMENT_AUTHOR.AUTHORID);
        public static final ForeignKey<EnterpriseuserRecord, UserprofileRecord> FKMRR9NOVKAQ55WUDE71D8MI3SE = createForeignKey(com.mgl.jpa.mapping.samples.jooq.Keys.KEY_USERPROFILE_PRIMARY, Enterpriseuser.ENTERPRISEUSER, "FKmrr9novkaq55wude71d8mi3se", Enterpriseuser.ENTERPRISEUSER.ID);
        public static final ForeignKey<EnterpriseuserPermissionRecord, EnterpriseuserRecord> FKRL7GCV4IWAOP529L1PRF4SM8H = createForeignKey(com.mgl.jpa.mapping.samples.jooq.Keys.KEY_ENTERPRISEUSER_PRIMARY, EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION, "FKrl7gcv4iwaop529l1prf4sm8h", EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION.ENTERPRISEUSER);
        public static final ForeignKey<RegularuserRecord, UserprofileRecord> FK3WYV5WNI5YL2LL2C75ED2CMRF = createForeignKey(com.mgl.jpa.mapping.samples.jooq.Keys.KEY_USERPROFILE_PRIMARY, Regularuser.REGULARUSER, "FK3wyv5wni5yl2ll2c75ed2cmrf", Regularuser.REGULARUSER.ID);
        public static final ForeignKey<UserprofileRecord, CompanyRecord> FK5GU1O4X2CAOFNE9NDBG001YYW = createForeignKey(com.mgl.jpa.mapping.samples.jooq.Keys.KEY_COMPANY_PRIMARY, Userprofile.USERPROFILE, "FK5gu1o4x2caofne9ndbg001yyw", Userprofile.USERPROFILE.COMPANY_ID);
    }
}
