/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq;


import com.mgl.jpa.mapping.samples.jooq.tables.Avatar;
import com.mgl.jpa.mapping.samples.jooq.tables.Company;
import com.mgl.jpa.mapping.samples.jooq.tables.Document;
import com.mgl.jpa.mapping.samples.jooq.tables.DocumentAuthor;
import com.mgl.jpa.mapping.samples.jooq.tables.Enterpriseuser;
import com.mgl.jpa.mapping.samples.jooq.tables.EnterpriseuserPermission;
import com.mgl.jpa.mapping.samples.jooq.tables.Regularuser;
import com.mgl.jpa.mapping.samples.jooq.tables.Userprofile;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jpa
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jpa.Avatar</code>.
     */
    public static final Avatar AVATAR = com.mgl.jpa.mapping.samples.jooq.tables.Avatar.AVATAR;

    /**
     * The table <code>jpa.Company</code>.
     */
    public static final Company COMPANY = com.mgl.jpa.mapping.samples.jooq.tables.Company.COMPANY;

    /**
     * The table <code>jpa.Document</code>.
     */
    public static final Document DOCUMENT = com.mgl.jpa.mapping.samples.jooq.tables.Document.DOCUMENT;

    /**
     * The table <code>jpa.Document_Author</code>.
     */
    public static final DocumentAuthor DOCUMENT_AUTHOR = com.mgl.jpa.mapping.samples.jooq.tables.DocumentAuthor.DOCUMENT_AUTHOR;

    /**
     * The table <code>jpa.EnterpriseUser</code>.
     */
    public static final Enterpriseuser ENTERPRISEUSER = com.mgl.jpa.mapping.samples.jooq.tables.Enterpriseuser.ENTERPRISEUSER;

    /**
     * The table <code>jpa.EnterpriseUser_Permission</code>.
     */
    public static final EnterpriseuserPermission ENTERPRISEUSER_PERMISSION = com.mgl.jpa.mapping.samples.jooq.tables.EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION;

    /**
     * The table <code>jpa.RegularUser</code>.
     */
    public static final Regularuser REGULARUSER = com.mgl.jpa.mapping.samples.jooq.tables.Regularuser.REGULARUSER;

    /**
     * The table <code>jpa.UserProfile</code>.
     */
    public static final Userprofile USERPROFILE = com.mgl.jpa.mapping.samples.jooq.tables.Userprofile.USERPROFILE;
}
