/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company implements Serializable {

    private static final long serialVersionUID = -908689757;

    private Long      id;
    private Long      version;
    private Timestamp creationts;
    private Timestamp lastmodificationts;
    private String    city;
    private String    street;
    private String    email;
    private String    firstname;
    private String    lastname;
    private String    organisationname;

    public Company() {}

    public Company(Company value) {
        this.id = value.id;
        this.version = value.version;
        this.creationts = value.creationts;
        this.lastmodificationts = value.lastmodificationts;
        this.city = value.city;
        this.street = value.street;
        this.email = value.email;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.organisationname = value.organisationname;
    }

    public Company(
        Long      id,
        Long      version,
        Timestamp creationts,
        Timestamp lastmodificationts,
        String    city,
        String    street,
        String    email,
        String    firstname,
        String    lastname,
        String    organisationname
    ) {
        this.id = id;
        this.version = version;
        this.creationts = creationts;
        this.lastmodificationts = lastmodificationts;
        this.city = city;
        this.street = street;
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.organisationname = organisationname;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Timestamp getCreationts() {
        return this.creationts;
    }

    public void setCreationts(Timestamp creationts) {
        this.creationts = creationts;
    }

    public Timestamp getLastmodificationts() {
        return this.lastmodificationts;
    }

    public void setLastmodificationts(Timestamp lastmodificationts) {
        this.lastmodificationts = lastmodificationts;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getOrganisationname() {
        return this.organisationname;
    }

    public void setOrganisationname(String organisationname) {
        this.organisationname = organisationname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Company (");

        sb.append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(creationts);
        sb.append(", ").append(lastmodificationts);
        sb.append(", ").append(city);
        sb.append(", ").append(street);
        sb.append(", ").append(email);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(organisationname);

        sb.append(")");
        return sb.toString();
    }
}
