/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentAuthor implements Serializable {

    private static final long serialVersionUID = -1391214956;

    private Long documentid;
    private Long authorid;

    public DocumentAuthor() {}

    public DocumentAuthor(DocumentAuthor value) {
        this.documentid = value.documentid;
        this.authorid = value.authorid;
    }

    public DocumentAuthor(
        Long documentid,
        Long authorid
    ) {
        this.documentid = documentid;
        this.authorid = authorid;
    }

    public Long getDocumentid() {
        return this.documentid;
    }

    public void setDocumentid(Long documentid) {
        this.documentid = documentid;
    }

    public Long getAuthorid() {
        return this.authorid;
    }

    public void setAuthorid(Long authorid) {
        this.authorid = authorid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DocumentAuthor (");

        sb.append(documentid);
        sb.append(", ").append(authorid);

        sb.append(")");
        return sb.toString();
    }
}
