/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document implements Serializable {

    private static final long serialVersionUID = -452193097;

    private String  documentkind;
    private Long    id;
    private Long    version;
    private Integer pagescnt;
    private String  title;
    private String  url;
    private String  filepath;

    public Document() {}

    public Document(Document value) {
        this.documentkind = value.documentkind;
        this.id = value.id;
        this.version = value.version;
        this.pagescnt = value.pagescnt;
        this.title = value.title;
        this.url = value.url;
        this.filepath = value.filepath;
    }

    public Document(
        String  documentkind,
        Long    id,
        Long    version,
        Integer pagescnt,
        String  title,
        String  url,
        String  filepath
    ) {
        this.documentkind = documentkind;
        this.id = id;
        this.version = version;
        this.pagescnt = pagescnt;
        this.title = title;
        this.url = url;
        this.filepath = filepath;
    }

    public String getDocumentkind() {
        return this.documentkind;
    }

    public void setDocumentkind(String documentkind) {
        this.documentkind = documentkind;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Integer getPagescnt() {
        return this.pagescnt;
    }

    public void setPagescnt(Integer pagescnt) {
        this.pagescnt = pagescnt;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFilepath() {
        return this.filepath;
    }

    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Document (");

        sb.append(documentkind);
        sb.append(", ").append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(pagescnt);
        sb.append(", ").append(title);
        sb.append(", ").append(url);
        sb.append(", ").append(filepath);

        sb.append(")");
        return sb.toString();
    }
}
