/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Enterpriseuser implements Serializable {

    private static final long serialVersionUID = -212617789;

    private String    registrationsource;
    private Timestamp signupts;
    private Timestamp creationts;
    private Timestamp lastmodificationts;
    private Long      id;

    public Enterpriseuser() {}

    public Enterpriseuser(Enterpriseuser value) {
        this.registrationsource = value.registrationsource;
        this.signupts = value.signupts;
        this.creationts = value.creationts;
        this.lastmodificationts = value.lastmodificationts;
        this.id = value.id;
    }

    public Enterpriseuser(
        String    registrationsource,
        Timestamp signupts,
        Timestamp creationts,
        Timestamp lastmodificationts,
        Long      id
    ) {
        this.registrationsource = registrationsource;
        this.signupts = signupts;
        this.creationts = creationts;
        this.lastmodificationts = lastmodificationts;
        this.id = id;
    }

    public String getRegistrationsource() {
        return this.registrationsource;
    }

    public void setRegistrationsource(String registrationsource) {
        this.registrationsource = registrationsource;
    }

    public Timestamp getSignupts() {
        return this.signupts;
    }

    public void setSignupts(Timestamp signupts) {
        this.signupts = signupts;
    }

    public Timestamp getCreationts() {
        return this.creationts;
    }

    public void setCreationts(Timestamp creationts) {
        this.creationts = creationts;
    }

    public Timestamp getLastmodificationts() {
        return this.lastmodificationts;
    }

    public void setLastmodificationts(Timestamp lastmodificationts) {
        this.lastmodificationts = lastmodificationts;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Enterpriseuser (");

        sb.append(registrationsource);
        sb.append(", ").append(signupts);
        sb.append(", ").append(creationts);
        sb.append(", ").append(lastmodificationts);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
