/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userprofile implements Serializable {

    private static final long serialVersionUID = 558154400;

    private String userkind;
    private Long   id;
    private Long   version;
    private String city;
    private String street;
    private String email;
    private String firstname;
    private String lastname;
    private Long   companyId;

    public Userprofile() {}

    public Userprofile(Userprofile value) {
        this.userkind = value.userkind;
        this.id = value.id;
        this.version = value.version;
        this.city = value.city;
        this.street = value.street;
        this.email = value.email;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.companyId = value.companyId;
    }

    public Userprofile(
        String userkind,
        Long   id,
        Long   version,
        String city,
        String street,
        String email,
        String firstname,
        String lastname,
        Long   companyId
    ) {
        this.userkind = userkind;
        this.id = id;
        this.version = version;
        this.city = city;
        this.street = street;
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.companyId = companyId;
    }

    public String getUserkind() {
        return this.userkind;
    }

    public void setUserkind(String userkind) {
        this.userkind = userkind;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Long getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userprofile (");

        sb.append(userkind);
        sb.append(", ").append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(city);
        sb.append(", ").append(street);
        sb.append(", ").append(email);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(companyId);

        sb.append(")");
        return sb.toString();
    }
}
