/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.records;


import com.mgl.jpa.mapping.samples.jooq.tables.EnterpriseuserPermission;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnterpriseuserPermissionRecord extends TableRecordImpl<EnterpriseuserPermissionRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -2077380112;

    /**
     * Setter for <code>jpa.EnterpriseUser_Permission.enterpriseUser</code>.
     */
    public void setEnterpriseuser(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jpa.EnterpriseUser_Permission.enterpriseUser</code>.
     */
    public Long getEnterpriseuser() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jpa.EnterpriseUser_Permission.permission</code>.
     */
    public void setPermission(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jpa.EnterpriseUser_Permission.permission</code>.
     */
    public String getPermission() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION.ENTERPRISEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getEnterpriseuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnterpriseuserPermissionRecord value1(Long value) {
        setEnterpriseuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnterpriseuserPermissionRecord value2(String value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnterpriseuserPermissionRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnterpriseuserPermissionRecord
     */
    public EnterpriseuserPermissionRecord() {
        super(EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION);
    }

    /**
     * Create a detached, initialised EnterpriseuserPermissionRecord
     */
    public EnterpriseuserPermissionRecord(Long enterpriseuser, String permission) {
        super(EnterpriseuserPermission.ENTERPRISEUSER_PERMISSION);

        set(0, enterpriseuser);
        set(1, permission);
    }
}
