/**
 * This class is generated by jOOQ
 */
package com.mgl.jpa.mapping.samples.jooq.tables.records;


import com.mgl.jpa.mapping.samples.jooq.tables.Userprofile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserprofileRecord extends UpdatableRecordImpl<UserprofileRecord> implements Record9<String, Long, Long, String, String, String, String, String, Long> {

    private static final long serialVersionUID = -436704031;

    /**
     * Setter for <code>jpa.UserProfile.userKind</code>.
     */
    public void setUserkind(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.userKind</code>.
     */
    public String getUserkind() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jpa.UserProfile.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>jpa.UserProfile.version</code>.
     */
    public void setVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>jpa.UserProfile.city</code>.
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.city</code>.
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jpa.UserProfile.street</code>.
     */
    public void setStreet(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.street</code>.
     */
    public String getStreet() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jpa.UserProfile.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jpa.UserProfile.firstName</code>.
     */
    public void setFirstname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jpa.UserProfile.lastName</code>.
     */
    public void setLastname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.lastName</code>.
     */
    public String getLastname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jpa.UserProfile.company_id</code>.
     */
    public void setCompanyId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>jpa.UserProfile.company_id</code>.
     */
    public Long getCompanyId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Long, Long, String, String, String, String, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Long, Long, String, String, String, String, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Userprofile.USERPROFILE.USERKIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Userprofile.USERPROFILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Userprofile.USERPROFILE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Userprofile.USERPROFILE.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Userprofile.USERPROFILE.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Userprofile.USERPROFILE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Userprofile.USERPROFILE.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Userprofile.USERPROFILE.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Userprofile.USERPROFILE.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserkind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value1(String value) {
        setUserkind(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value2(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value3(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value4(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value5(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value6(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value7(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value8(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord value9(Long value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserprofileRecord values(String value1, Long value2, Long value3, String value4, String value5, String value6, String value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserprofileRecord
     */
    public UserprofileRecord() {
        super(Userprofile.USERPROFILE);
    }

    /**
     * Create a detached, initialised UserprofileRecord
     */
    public UserprofileRecord(String userkind, Long id, Long version, String city, String street, String email, String firstname, String lastname, Long companyId) {
        super(Userprofile.USERPROFILE);

        set(0, userkind);
        set(1, id);
        set(2, version);
        set(3, city);
        set(4, street);
        set(5, email);
        set(6, firstname);
        set(7, lastname);
        set(8, companyId);
    }
}
